DioxusLabs/blitz

Cargo.toml
examples/test.rs
src/application.rs
src/layout.rs
src/lib.rs
src/render.rs
src/style.rs
src/util.rs
src/window.rs

- Lazy layout and attributes (currently only color and borders)
- Div border rendering
- Basic text rendering

Basic Rendering with piet-wgpu and tao

---

Cargo.toml
examples/buttons.rs
examples/test.rs
src/application.rs
src/events.rs
src/focus.rs
src/layout.rs
src/lib.rs
src/mouse.rs
src/node.rs
src/render.rs
src/style.rs
src/util.rs

Makes blitz work with updated version of Dioxus, lightningcss, and taffy.

update to sync with master branch of Dioxus

---

src/events.rs
src/util.rs

Fixes spacebar and super left and right key events.
closes #6

Fix key events

---

src/events.rs

When an element is hovered in the buttons example and then the mouse goes off the screen in one frame the onmouseexit event was not triggered. This PR fixes that issue.
closes #5

fix onmouseexit off screen

---

blitz-core/Cargo.toml
blitz-core/src/application.rs
blitz-core/src/layout.rs
blitz-core/src/render.rs
blitz-core/src/style.rs
examples/buttons.rs
examples/list.rs

Due to too much conflicts on #19 , reopen a branch and move changes to here.

add font size support

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_requst.md
.github/dependabot.yml
.github/workflows/macos.yml
.github/workflows/main.yml
.github/workflows/windows.yml

Creates a CI with testing and linting and an issue template and funding information for the Blitz project. The configuration is modified from the main [Dioxus .github](https://github.com/DioxusLabs/dioxus/tree/master/.github)

Create CI and issue template

---

.github/workflows/main.yml
blitz-core/src/lib.rs
blitz-core/src/style.rs

Adds gtk as a dependency to CI to make the Linux tests run correctly

Fix CI dependancies

---

blitz-core/README.md
blitz-core/src/style/background/linear_gradient.rs

Fix a few typos

---

Cargo.toml
examples/border.rs
examples/interactive.rs
examples/layout_debug.rs
packages/blitz/src/render.rs
packages/dioxus-blitz/src/documents/dioxus_document.rs
packages/dioxus-blitz/src/documents/event_handler.rs
packages/dioxus-blitz/src/documents/mod.rs
packages/dioxus-blitz/src/lib.rs
packages/dioxus-blitz/src/window.rs
packages/dom/Cargo.toml
packages/dom/src/document.rs
packages/dom/src/events.rs
packages/dom/src/layout.rs
packages/dom/src/lib.rs
packages/dom/src/node.rs

Wires up our interactivity system from dioxus into Blitz - basic buttons clicks and cursor state works now!
This is currently very rough code but can easily be picked up to make it a bit more refined.
Some methods are just meaningless/pointless/poorly organized.
https://github.com/DioxusLabs/blitz/assets/10237910/d971fc24-6626-46e2-9545-3e8121138849

Make the dioxus implementation interactive - just clicks for now

---

packages/blitz/Cargo.toml
packages/dioxus-blitz/Cargo.toml
packages/dioxus-blitz/src/window.rs
packages/dom/Cargo.toml

No point having these sat around. We can always add them back later if we need them.

Remove unused dependencies

---

.github/workflows/ci.yml

Use opt-level = 0 in CI

---

Cargo.toml
examples/text.rs
packages/blitz/Cargo.toml
packages/blitz/src/render.rs
packages/dioxus-blitz/Cargo.toml
packages/dioxus-blitz/src/documents/dioxus_document.rs
packages/dioxus-blitz/src/lib.rs
packages/dioxus-blitz/src/window.rs
packages/dom/Cargo.toml

#83 
Starts replacement of `println!`/`dbg!` logging with structured logging via the `tracing` crate

Tracing integration

---

packages/blitz/src/lib.rs
packages/dioxus-blitz/src/lib.rs
packages/dom/src/lib.rs

Adds basic root docs for the new feature flags in each crate

Document feature flags

---

packages/blitz/src/renderer/render.rs

This one has improved vello bug workarounds.

Implement clipped rendering (with workaround for some vello bugs)

---

.gitignore
Cargo.toml
examples/output/wpt/.gitkeep
examples/wpt.rs
packages/blitz-dom/src/document.rs
packages/blitz-net/src/lib.rs

Initial rust-based WPT runner

---

packages/blitz-renderer-vello/src/renderer/render.rs

This removes a bit of complexity from the renderer

Simplify inline box rendering

---

apps/readme/Cargo.toml
apps/readme/src/main.rs
apps/readme/src/readme_application.rs
packages/blitz-dom/src/document.rs
packages/blitz-shell/src/window.rs

Automatically reloads files on changes if previewing a local file.

Implement hot-reloading for readme app

---

examples/form.rs
packages/blitz-dom/assets/default.css
packages/blitz-dom/src/document.rs
packages/blitz-dom/src/events/mouse.rs
packages/blitz-dom/src/layout/construct.rs
packages/blitz-renderer-vello/src/renderer/render.rs

Working radio button functionality, along with the default rendering.

Radio Buttons

---

Cargo.toml
packages/blitz-dom/src/document.rs
packages/blitz-dom/src/events/mod.rs
packages/blitz-dom/src/events/mouse.rs
packages/blitz-dom/src/node.rs
packages/blitz-html/src/html_document.rs
packages/blitz-shell/src/window.rs
packages/blitz-traits/Cargo.toml
packages/blitz-traits/src/document.rs
packages/blitz-traits/src/events.rs
packages/blitz-traits/src/lib.rs
packages/dioxus-native/src/dioxus_document.rs

This is a smaller PR than #179, which only supports selecting the input box text with the mouse.

feat: Support text box mouse selection

---

packages/dioxus-native/src/mutation_writer.rs

Currently setting a value to an `img` tag `src` attribute in dioxus does nothing when using the dioxus-native renderer. Like:
````
img {
src: "some_image_filepath_or_url"
}
````
With this small change, when a change on this attribute is reflected into the real dom, it also triggers a resource load for the image so the image is actually displayed (provided there is a `net_provider` configured).

Support img src attribute for dioxus-native

---

examples/box_shadow.rs
packages/blitz-paint/src/multicolor_rounded_rect.rs
packages/blitz-paint/src/render/box_shadow.rs

* Fix shadow clipping.
* Fixed shadow rendering order.
* Support for the spread property of shadows.

fix: Fixed some rendering behaviors of box-shadow

---

.github/workflows/wpt.yml

This PR just runs the tests. It doesn't record the results.

Run WPT tests in CI

---

examples/assets/animation.html
examples/inner_html.rs
examples/screenshot.rs
packages/blitz-dom/src/document.rs
packages/blitz-dom/src/mutator.rs
packages/blitz-dom/src/stylo.rs
packages/blitz-shell/src/window.rs
wpt/runner/src/test_runners/mod.rs

To test: `cargo run -rp readme ./examples/assets/animation.html` and try hovering the box.
https://github.com/user-attachments/assets/ea41723e-ab6b-4ba2-aa12-d41db2bc672b

CSS animations and transitions

---

Cargo.lock
Cargo.toml
apps/readme/Cargo.toml
examples/counter/Cargo.toml
examples/todomvc/Cargo.toml
packages/blitz-dom/Cargo.toml
packages/blitz/Cargo.toml
packages/debug_timer/Cargo.toml
wpt/runner/Cargo.toml

Fixes https://github.com/DioxusLabs/blitz/issues/270

Release blitz v0.2.0
