src/render.rs
Taffy outputs layout relative to the parent. Accumulate the offsets to calculate the current position.
=> fix child layout

src/application.rs
When an element is hovered in the buttons example it doesn't immediately cause a redraw. This fixes that regression created in #10.
=> Fix redrawing

LICENSE-APACHE.txt, LICENSE-MIT.txt
Adds the license files for the licenses listed in the Cargo.toml
=> Add apache 2.0 and MIT licenses

Cargo.toml, README.md
This applies a patch for naga to fix macOS support (https://github.com/gfx-rs/naga/pull/2099).
This should be reverted once wgpu 15 is released.
=> Add patch for naga to fix macOS support

Cargo.toml, src/application.rs, src/focus.rs
This bumps the Vello version to make the project compile again. The revision we previously relied on had it's own git [dependencies that were not pinned](https://github.com/linebender/vello/blob/dfde0936e5064ac8bb2765e1c3fdc1d5ac757a83/vello/Cargo.toml#L15). The current revision has pinned git dependencies
=> Bump Vello Revision

Cargo.toml, README.md
- Upgrades dependencies
- Upgrades vello and wgpu (naga patch for macOS no longer required)
- Pins dioxus version (this was otherwise causing a compile error due to blitz requesting an older version of lightningcss which caused cargo to choose an older version of dioxus).
=> Upgrade dependencies + pin dioxus version

Cargo.toml, blitz-core/Cargo.toml, blitz-core/src/application.rs, blitz-core/src/layout.rs, examples/css_grid_buttons.rs
Depends on: https://github.com/DioxusLabs/dioxus/pull/1030
Support CSS Grid and gain the fixes from Taffy 0.3
- ~Point deps at https://github.com/DioxusLabs/dioxus/pull/1030~ PR has been merged, so this change has now been reverted.
- Upgrade Taffy version
- Add `.clone`s because `Style` is no longer `Copy`
- Add CSS Grid example
Waiting on https://github.com/parcel-bundler/lightningcss/pull/490 in order to support `repeat()` syntax, but I don't think that ought to block this being merged.
=> Upgrade to Taffy 0.3

.github/workflows/macos.yml, .github/workflows/main.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/DioxusLabs/blitz/actions/runs/5034105924:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct invocations of …
=> Replace unmaintained actions-rs/* actions in CI workflows

blitz-core/src/text/mod.rs, blitz-core/src/util.rs
- Vello now returns `color.to_rgb()` as a Result(CssColor, ())
- Fill all match branches of FontSizeProperty abs_val
=> fixes build for newest versions of dependencies

blitz-core/Cargo.toml
In May, the `layout_attributes` were moved behind a feature flag, so we need to build with that feature enabled.
=> blitz-core: Fix build with dioxus-native-core.

.github/workflows/macos.yml, .github/workflows/main.yml, .github/workflows/windows.yml
in #43 and #41, CI did not run because the blitz-core path was ignored. This adds blitz-core to the files CI listens to so that it will run when future PRs change Blitz core
=> Run CI when blitz core changes

Cargo.toml, blitz-core/Cargo.toml
This improves the usage of automated tooling which consumes the license information.
=> Use SPDX 2.1 license expression.

Cargo.toml, blitz-core/Cargo.toml
Building for wasm32 doesn't work and it seems like this is intended to be a native target.
=> Remove wasm32 target dependencies.

Cargo.toml, blitz-core/Cargo.toml
upgraded the keyboard-types from 0.6.2 to 0.7.0 
according to this issue and fix https://github.com/DioxusLabs/blitz/issues/52#issue-1891053880
=> upgraded the keyboard-types library

blitz-core/src/text/mod.rs
Fills in the xxxlarge font size. Currently if blitz finds a xxxlarge font size it will panic
Followup to #40
=> Fill in xxxlarge font size

blitz-core/Cargo.toml, blitz-core/src/style/foreground.rs
Looks like Dioxus updated their cssparser dependency. This fixes Blitz to work with that.
=> Fix cssparser dependency

Cargo.toml, packages/blitz-core/Cargo.toml, packages/blitz-core/src/events.rs, packages/blitz/Cargo.toml, packages/blitz/examples/buttons.rs, packages/blitz/src/lib.rs, packages/plasmo/src/hooks.rs
Updates Blitz to compile with the git version of dioxus. Only the button example is currently updated to run with dioxus 0.5 because this version of blitz will be replaced by blitz-stylo.
Fixes the CI failure in https://github.com/DioxusLabs/docsite/pull/220
=> Update blitz to the git version of dioxus

packages/blitz/src/render.rs, packages/dioxus-blitz/src/window.rs
Project could not be compiled on Linux due to missing import. This import was added.
Crashes when resizing were also common so they were solved with an early return.
Lastly, the `get_cursor` function sometimes unwraped a `None` variant on an `Option` so the `unwrap` was replaced with an error propagation syntax.
=> Fix building and few crashes on Linux

packages/dom/src/util.rs
When splitting the string into substrings, the splitting logic could `panic` because it did not respect character boundaries. This could be easily triggered with a non-ascii text in the DOM.
=> Make debug printing aware of character boundaries

packages/dioxus-blitz/Cargo.toml, packages/dioxus-blitz/src/lib.rs, packages/dioxus-blitz/src/waker.rs, packages/dioxus-blitz/src/window.rs
Replaces the `tao` backend with `winit` in anticipation of `accesskit` and `masonry` features.
I wanted to make a quick working draft for now to see how this change integrates with the project. So far I haven't noticed any different behavior between the two crates 👍
=> Replace tao with winit

.github/workflows/ci.yml, .gitignore, .vscode/settings.json, CONTRIBUTING.MD, packages/dioxus-blitz/src/window.rs
* Fixes menu bar on Windows
* Refactor menu bar initialization and add it to `View`
* Remove GTK menu for now
- This is the biggest change I've noticed so far from `tao`. I'd love to dig deeper into this but I'm not sure how we can access a potential `gtk::Window` from the `winit::Window` yet.
* Set default Rust toolchain to latest stable
* Remove mobile CI for now
* Install required Ubuntu dependencies
=> Follow up for `winit` backend and CI

.github/workflows/ci.yml, .gitignore, .vscode/settings.json, CONTRIBUTING.MD, packages/dioxus-blitz/Cargo.toml, packages/dioxus-blitz/src/lib.rs, packages/dioxus-blitz/src/window.rs
Needed to fix some issues regarding muda - looks like we never implemented some of it.
Had to allow deprecated on the closure approach for winit.
Stole our CI for multiplatform from dioxus
(todo) override opt-level for CI
=> Fix cross-platform mudabar, wire up better CI

packages/blitz/src/render.rs
Fix #80.
When the viewport_height is greater than the content_height, the scroll_offset becomes positive.
=> fix: scroll clamping

examples/parse_debug.rs
There is no "google_bits" folder, its renamed to "assets".
=> Fix incorrect file path in parse_debug example

packages/blitz/Cargo.toml, packages/blitz/src/renderer/render.rs, packages/dom/Cargo.toml, packages/dom/src/htmlsink.rs, packages/dom/src/layout/mod.rs, packages/dom/src/node.rs, packages/dom/src/util.rs
Fixes #99 
Pretty naive (and adds ~3mb to binary size), but this gives us basic support for SVGs included as `<img>` tags
=> Basic `vello_svg` based SVG support

packages/dioxus-blitz/src/application.rs, packages/dioxus-blitz/src/lib.rs, packages/dioxus-blitz/src/window.rs
@jkelleyrtp I'm assuming that we were only previously using the closure because you hadn't gotten around to changing it rather than because there was a specific reason to prefer that API?
=> Use `ApplicationHandler` trait for winit integration

.gitignore, Cargo.toml, examples/output/.gitkeep, examples/screenshot.rs, packages/blitz/Cargo.toml, packages/blitz/src/renderer.rs, packages/dioxus-blitz/src/documents/html_document.rs, packages/dioxus-blitz/src/documents/mod.rs, packages/dioxus-blitz/src/lib.rs, packages/dom/src/document.rs
The new example renders to an image which it writes to the `examples/output` directory.
=> Add screenshot example

packages/dioxus-blitz/src/documents/dioxus_document.rs
Fixes #81 - Currently, dioxus apps without a single root element crash when rendered in blitz. This fixes that by creating a virtual `<html>` root element. 
I experimented with a couple of other approaches as well, such as:
- treating Document nodes as an element as well - a bit of an impedance mismatch since stylo makes a distinction between documents and elements
- abolishing the concept of a root element and rendering all child elements of the root node - mismatch since taffy wants to draw a root element.
So this way seemed to be the best way to make it work out. With this fix you should find that the dioxus examples such as `bare_style` and `tailwind` no longer crash, and render correctly as far as they can.
=> Add a root html element in Dioxus integration

Cargo.toml, examples/tailwind.rs, packages/blitz/Cargo.toml, packages/blitz/src/renderer.rs, packages/blitz/src/renderer/render.rs
Adds support for rendering box-shadow, using the [blur-rect](https://github.com/msiglreith/vello/tree/blur-rect) branch of vello.
Also updates the tailwind example to render `#cool` with a black shadow, and #cool-inset with an inset shadow, to demo support.
*Caveats*
- Linked to a fork of vello
- Vello support is only of a single border radius, so it averages all corner's border radii to get the shadow radius
- Ignores the spread radius parameter, and only uses blur radius. Not sure how spread radius is meant to be handled?
=> Implement box-shadow drawing

examples/scroll.rs, packages/blitz/src/renderer/render.rs, packages/dioxus-blitz/src/window.rs, packages/dom/src/document.rs, packages/dom/src/node.rs, packages/dom/src/viewport.rs
Implements scrolling on mouse-wheel events, of any node which is hovered. When a node has hit its scroll boundary, scrolling bubbles up to the node's parent, all the way up to the root element. The root (html) element is sized to the viewport (is this technically the right thing to do?) and therefore will automatically handle root-level scrolling.
Adds an example `scrolling` which demos scrolling in the middle element. Scrolling the root element can be tested by resizing the window smaller than the content and scrolling, otherwise the tailwind example has a large content area and should be scrollable too.
Todo: Touch scrolling, flinging with momentum (even with mouse wheel? chromium does this).
=> Non-root  scrolling

packages/dioxus-blitz/src/lib.rs, packages/dioxus-blitz/src/window.rs
Skips setting the default window size to 800x600 when compiling for mobile
Fixes #124
=> Skip setting default window size on mobile

examples/gradient.rs, packages/blitz/src/renderer/render.rs
This PR revives the long-stalled PR from https://github.com/jkelleyrtp/stylo-dioxus/pull/4.
It adds full gradient support. Note that due to Vello's behavior, it follows the SVG schema rather than the web schema by default ("transparent" is #00000000 rather than #FFFFFF00 in color mixing), so some gradients may differ.
=> Port full gradient support to blitz

examples/form.rs, packages/blitz/src/renderer/render.rs, packages/dioxus-blitz/src/documents/dioxus_document.rs, packages/dom/src/document.rs, packages/dom/src/layout/construct.rs, packages/dom/src/node.rs, packages/dom/src/stylo.rs
Keeps checkbox checked value internally in `NodeSpecificData`, instead of setting the `checked` attribute on the node. This  more closely aligns it with the w3c spec. 
In addition, as the checked property in rsx is now interpreted specially instead of being forwarded directly to the attribute, it can now handle boolean values as well as strings, such that `checked: checkbox_checked(),` rsx now works.
Last of all the 'value' property of formevent now reflects the checked state instead of the value attribute of the checked element, aligning it with dioxus web, and ensuring that FormEvent.checked() is correct.
=> Checkbox internal state

Cargo.toml, packages/dom/src/htmlsink.rs, packages/dom/src/stylo.rs
This is a fairly minor Stylo upgrade but it required upgrading past a breaking change to html5ever which wasn't actually compatible with Blitz. So I have also submitted https://github.com/servo/html5ever/pull/553 to make it work again.
=> Upgrade stylo and html5ever

packages/blitz/src/renderer/render.rs, packages/dom/src/document.rs, packages/dom/src/layout/construct.rs, packages/dom/src/node.rs
- Revert back to using parley layout regardless if rendering a single glyph or string
- Align the marker layout with baseline of first line of text in the list item
=> List item improvements

packages/dom/src/layout/construct.rs
If list item data was set previously, eg due to style sheets not being loaded yet, it previously would not be reverted if it now no longer should exist. This fixes that. This fixes eg. rendering bullets on https://alistapart.com when they should not appear.
=> Unset list item data if previously set

packages/dom/Cargo.toml, packages/dom/src/util.rs
This adds support for woff2 and filters out unsupported font types.
=> Add woff2 support

examples/assets/google.html, packages/blitz-dom/src/document.rs, packages/blitz-dom/src/htmlsink.rs, packages/blitz-dom/src/net.rs, packages/blitz-dom/src/node.rs, packages/blitz-dom/src/util.rs, packages/blitz-renderer-vello/src/renderer/render.rs
This is a slightly hacky approach which serializes SVG subtrees of the DOM to string before parsing that string with usvg. But it gets us minimal support quickly.
=> Inline SVG support

packages/blitz-dom/src/document.rs, packages/blitz-dom/src/html_document.rs, packages/blitz-dom/src/htmlsink.rs, packages/blitz-dom/src/layout/construct.rs, packages/blitz-dom/src/layout/mod.rs, packages/blitz-dom/src/net.rs, packages/blitz-dom/src/node.rs, packages/blitz-dom/src/stylo.rs, packages/blitz-dom/src/util.rs, packages/blitz-renderer-vello/src/renderer/render.rs
What is supported:
- Raster image backgrounds
- SVG backgrounds
- Multiple background images
What is not supported:
- Any background size/position/repeat styles
=> Initial background image support

packages/blitz-renderer-vello/src/renderer/render.rs
- Renames `element`  to `node`
- Renames `pos` to `box_position` and `content_position`
- Renames `size` to `content_size`
- Adds an `element` fields to `ElementCx` which is of type `ElementNodeData` because we `node.element_data().unwrap()` 6 times
- and move some code into their own functions  (`draw_text_input_text`, `draw_marker` and `draw_children`)
=> chore(refactor): improve code readability in renderer

apps/readme/src/main.rs, apps/wpt/src/net_provider.rs, examples/screenshot.rs, packages/blitz-dom/src/document.rs, packages/blitz-dom/src/htmlsink.rs, packages/blitz-dom/src/net.rs, packages/blitz-dom/src/stylo.rs, packages/blitz-net/src/lib.rs, packages/blitz-traits/src/net.rs, packages/dioxus-native/src/application.rs, packages/dioxus-native/src/lib.rs, packages/dioxus-native/src/waker.rs, packages/dioxus-native/src/window.rs
This changes the net traits to pass the DocumentId through the chain of functions, which means that the `NetCallback` doesn't need to capture the WindowId when it is created. Which simplifies the whole setup.
=> Simplify net traits

packages/blitz-shell/src/application.rs
`new_event` method is called when a new event arrives on an event loop. Putting new event (in this case `BlitzEvent::Poll`) on the same event loop from this method causes this method to be called again. This ends up spamming event loop, 100% CPU utilization on some operating systems, and makes the `poll` "spin".
=> Remove event loop spamming when new event arrives

packages/dioxus-native/src/dioxus_document.rs
Using the `todo` macro causes a panic when this event is encountered. Noop is preferable in this case as it does not crash the application. This is especially annoying on platforms where `Ime::Enabled` event is sent upon application start even when the user is using a keyboard layout that does not need an IME support. 
There was added a "TODO" comment that informs about this feature being missing. Most IDEs and code editors have support/plugins/extensions to work with this type of comment and this type of comment is already used widely across the codebase. As such, the information about this feature not being implemented is not lost.
=> Remove use of the `todo` macro in event handling and add a comment about it being a todo

apps/readme/src/main.rs, apps/readme/src/readme_application.rs, apps/wpt/src/attr_test.rs, apps/wpt/src/main.rs, apps/wpt/src/ref_test.rs, examples/screenshot.rs, packages/blitz-dom/src/document.rs, packages/blitz-html/src/html_document.rs, packages/blitz-shell/src/application.rs, packages/blitz-shell/src/event.rs, packages/blitz-shell/src/window.rs, packages/blitz-traits/src/lib.rs, packages/blitz-traits/src/navigation.rs, packages/blitz/Cargo.toml, packages/blitz/src/lib.rs
For this we added another Variant to the BlitzEvent Enum and also made
DocumentLike return an Option<DocumentEvent> which currently just has
one Variant for following links.
I consider this a working POC, which needs to be fleshed out.
I didn't invest any time to make sure the DioxusSide still works. It
most likely won't because of the change in the trait definition.
@nicoburns If this is about what you want, I am happy to work on this, as my time allows. If I've diverged too far from your vision, that's also fine!
It's a working POC. When I open the readme app and click a link, the Document is replaced.
=> Add the ability to follow links

packages/blitz-dom/src/document.rs, packages/blitz-dom/src/events/mod.rs, packages/blitz-dom/src/node.rs, packages/blitz-dom/src/stylo.rs, packages/blitz-shell/src/window.rs, packages/dioxus-native/src/dioxus_document.rs
Click events are triggered after the mouse is pressed and released, and on the same node.
=> feat: Add mousedown and mouseup event

apps/wpt/src/net_provider.rs, packages/blitz-dom/src/net.rs, packages/blitz-dom/src/stylo.rs, packages/blitz-html/src/html_sink.rs, packages/blitz-net/src/lib.rs, packages/blitz-traits/src/net.rs
This allows the `NetHandler` implementation to modify the request used to fetch.
This is required when we intend to implement forms in the future.
=> Build requests via NetHandler

packages/blitz-renderer-vello/src/renderer/render.rs
=> fix: clipping translate of overflow hidden

packages/blitz-dom/src/document.rs, packages/blitz-dom/src/layout/construct.rs, packages/blitz-dom/src/node.rs, packages/blitz-renderer-vello/src/renderer.rs
Fixes this https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant Clippy lint
=> fix clippy warning large size between variants

apps/wpt/src/main.rs
Ran into this while testing https://github.com/linebender/parley/pull/315. This was causing a lot of reftests to be skipped.
Most of these tests still don't pass even with that Parley change, but it seems to be because the `width` attribute of the test `<div>` in the tests isn't being respected.
=> Handle single quotes in WPT reftest regex

examples/assets/border.html, examples/border.rs, packages/blitz-renderer-vello/src/renderer/multicolor_rounded_rect.rs, packages/blitz-renderer-vello/src/renderer/render.rs
When using the following styles, the `border-color` should appear `red` instead of `transparent`.
```css
#transparent {
border: 20px solid transparent;
background-color: red;
}
```
=> fix: Fixed the actual color displayed when border-color is transparent

packages/blitz-renderer-vello/src/renderer/multicolor_rounded_rect.rs, packages/blitz-renderer-vello/src/renderer/render.rs
Continuation of #202:
The cause of the issue in #202 was the size calculation for svg, so I removed my changes to svg in this PR (I plan to fix it in my next PR).
This PR adds 42 more test passes compared to main. (`cargo run -rp wpt css/css-backgrounds`)
=> feat: Support for background-clip property

packages/blitz-html/src/html_sink.rs
The `rel` attribute may be a list.
> [The type of relationships is given by the value of the rel attribute, which, if present, must have a value that is an unordered set of unique space-separated keywords. ](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel)
=> fix: loading style resources

Cargo.lock, Cargo.toml, apps/readme/src/main.rs, apps/readme/src/readme_application.rs, packages/blitz-dom/Cargo.toml, packages/blitz-dom/src/document.rs, packages/blitz-dom/src/events/keyboard.rs, packages/blitz-dom/src/events/mouse.rs, packages/blitz-dom/src/form.rs, packages/blitz-dom/src/lib.rs, packages/blitz-dom/src/net.rs, packages/blitz-dom/src/util.rs, packages/blitz-html/src/html_sink.rs, packages/blitz-shell/src/application.rs, packages/blitz-shell/src/event.rs, packages/blitz-traits/src/navigation.rs
Implements basic form submissions (fixes #178)
I tried following the specification, where it made sense.
Things that are missing are:
- `DomEvents`: [submit](https://html.spec.whatwg.org/multipage/indices.html#event-submit), [a click event when implicitly submitting](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission) and [formdata](https://html.spec.whatwg.org/multipage/indices.html#event-formdata) when constructing the entry list.
- `<select>`
- `multipart/form-data`
- [Image Buttons](https://html.spec.whatwg.org/multipage/input.html#image-button-state-(type=image))
=> Implement form submissions

Cargo.lock, Cargo.toml, examples/anyrender/Cargo.toml, examples/anyrender/src/main.rs
This PR adds a example of using `anyrender`, `anyrender_vello` and `anyrender_vello_cpu` together with a `winit` window.  By hitting the spacebar key, you can swap between an `anyrender_vello` and `anyrender_vello_cpu` backend.
The naming of this example is currently quite messy:
- The directory is called "examples/anyrender"
- The cargo package is called "anyrender_vello_example"
- The window title is "anyrender + winit demo"
I was going to clean this up, but figured I'd ask here to see if the maintainers had a preference before I make any more changes.
=> add anyrender+winit demo

examples/wgpu_texture/src/demo_renderer.rs, packages/anyrender_vello/src/custom_paint_source.rs, packages/anyrender_vello/src/wgpu_context.rs, packages/anyrender_vello/src/window_renderer.rs
Should make it easier to share device between dioxus and bevy in https://github.com/DioxusLabs/dioxus/pull/4360
=> Expose more wgpu types to custom paint sources

examples/inner_html.rs, packages/blitz-dom/src/config.rs, packages/blitz-dom/src/document.rs, packages/blitz-dom/src/html.rs, packages/blitz-dom/src/lib.rs, packages/blitz-dom/src/mutator.rs, packages/blitz-html/src/html_document.rs, packages/blitz-html/src/html_sink.rs, packages/blitz-html/src/lib.rs
- Provide `innerHTML` setter functionality
- Bltiz side of #240
- Add `HtmlParserProvider` trait so that we can inject HTML parsing functionality into `blitz-dom` (and users still have the option to bring their own HTML parser rather than being coupled to html5ever)
- Implement `HtmlParserProvider` in `blitz-html`
- Add `set_inner_html` method to `DocumentMutator`
- Add `children` method to `DocumentMutator`
- Add `inner_html` example to test functionlity
=> Implement `set_inner_html`

Cargo.lock, Cargo.toml, packages/blitz-dom/Cargo.toml, packages/blitz-dom/src/document.rs, packages/blitz-dom/src/events/ime.rs, packages/blitz-dom/src/events/keyboard.rs, packages/blitz-dom/src/events/mouse.rs, packages/blitz-dom/src/font_metrics.rs, packages/blitz-dom/src/layout/construct.rs, packages/blitz-dom/src/lib.rs, packages/blitz-dom/src/mutator.rs
Replaces the `DummyFontMetricsProvider` with one that actually does font fallback and extracts metrics from the font. This currently requires a Mutex around the `parley::FontContext` which isn't ideal but may be acceptable.
=> Implement FontMetricsProvider that actually provides correct metrics

Cargo.lock, Cargo.toml, examples/wgpu_texture/src/demo_renderer.rs, packages/anyrender/src/lib.rs, packages/anyrender/src/types.rs, packages/anyrender_svg/src/render.rs, packages/anyrender_svg/src/util.rs, packages/anyrender_vello/src/custom_paint_source.rs, packages/anyrender_vello/src/image_renderer.rs, packages/anyrender_vello/src/scene.rs, packages/anyrender_vello/src/wgpu_context.rs, packages/anyrender_vello/src/window_renderer.rs, packages/anyrender_vello_cpu/src/scene.rs, packages/blitz-dom/src/layout/inline.rs, packages/blitz-paint/src/gradient.rs, packages/blitz-paint/src/layers.rs, packages/blitz-paint/src/render.rs, packages/blitz-paint/src/render/background.rs
This pr updates blitz to use wgpu 26 and related dependencies to accommodate this update.
I've left a few questions marked with `//rydb:`, but otherwise, once vello and parley are updated, I can update those plus add any additional changes to this.
=> Update to wgpu 26, vello 0.6, vello_cpu 0.0.3, and parley pre-0.6
